
# paths
CONFIG_PATH = './rag-youtube.conf'

# defaults
DEFAULT_OLLAMA_URL = 'http://localhost:11434'
DEFAULT_OLLAMA_MODEL = 'mistral:latest'
DEFAULT_PERSIST_DIR = 'db'
DEFAULT_CONVERSATIONAL = 'true'
DEFAULT_EMBEDDINGS_MODEL = 'all-MiniLM-L6-v2'
DEFAULT_SPLIT_CHUNK_SIZE = 1000
DEFAULT_SPLIT_CHUNK_OVERLAP = 200
DEFAULT_SIMILARITY_DOCUMENT_COUNT = 4
