
# paths
CONFIG_PATH = './rag-youtube.conf'

# defaults
DEFAULT_DEBUG = 'false'
DEFAULT_OLLAMA_URL = 'http://localhost:11434'
DEFAULT_OLLAMA_MODEL = 'mistral:latest'
DEFAULT_DB_PERSIST_DIR = 'db'
DEFAULT_CHAIN_TYPE = 'conversation'
DEFAULT_DOC_CHAIN_TYPE = 'stuff'
DEFAULT_EMBEDDINGS_MODEL = 'all-MiniLM-L6-v2'
DEFAULT_SEARCH_TYPE = 'similarity'
DEFAULT_CUSTOM_PROMPTS = 'false'
DEFAULT_RETURN_SOURCES = 'false'
DEFAULT_SPLIT_CHUNK_SIZE = 2500
DEFAULT_SPLIT_CHUNK_OVERLAP = 500
DEFAULT_SIMILARITY_DOCUMENT_COUNT = 4
DEFAULT_MAX_SOURCE_SCORE = 1.0
